# Generated by Django 5.2.16 on 2026-07-13 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stock_in', 'Stock in'), ('stock_out', 'Stock out')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('reference_no', models.CharField(db_index=True, max_length=64)),
                ('requested_by', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('stock_before', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
