# Generated by Django 5.2.16 on 2026-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('unit', models.CharField(default='Each', max_length=32)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
